---
title: "Photodraw2-Descriptives"
author: "Bria Long"
date: "2/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(assertthat)
```

## Import descriptives csv

```{r cars}
d <- read.csv("photodraw2_descriptives/Photodraw2_AllDescriptives_1475_images_final_CDM_photodraw_e2_no_blanks.csv") %>%
  as.tibble() %>%
  mutate(age_numeric =as.numeric(str_split_fixed(age,'age',2)[,2]))
```


## Check that we don't have duplicate subIDs -- whooops, we do!
```{r}
prac_trials = c('this square','this shape','triangle','rectangle')
double_sessions <- d %>%
  distinct(subID,session_id) %>%
  group_by(subID) %>%
  summarize(num_sessions = n()) %>%
  filter(num_sessions > 1)

drawings_by_doubles <-  d %>%
  filter(subID %in% double_sessions$subID) %>%
  filter(!category %in% prac_trials) %>%
  group_by(subID,category) %>%
  summarize(num_drawings = n()) %>%
  filter(num_drawings >1) 

```

### There is one subID that was used twice (two different ages and sessionIds). Fix it!
```{r}
duplicate_sub_id = unique(drawings_by_doubles$subID)
to_fix <- d %>%
  filter(subID == duplicate_sub_id) 

unique(to_fix$age) ## two ages here -- age 5 and 7 with the same subID

# To match run sheet: 111418_6 & age7 stays as ID 111418_6
# To match run sheet: 111418_6 & age5 should instead be 111418_5
assert_that(sum(d$session_id=="111418_5")==0) # isn't it the database yet, so that's the error

## FIX IT : change subid to character so can replace value; change back to factor to keep tidy
d <- d %>%
  mutate(subID = as.character(subID)) %>%
  mutate(subID=replace(subID, subID=="111418_6" & age=="age5","111418_5")) %>%
  mutate(subID = as.factor(subID))

```

### Check our CB by age counterbalancing
```{r cb-by-age}
cb_by_age<- d %>%
  group_by(age_numeric,CB) %>%
  distinct(subID) %>%
  summarize(num_participants = n()) 

kable(cb_by_age)
```


### Check that we have equal numbers of trials by condition/age
```{r cat-by-condition-by-age}

d %>%
  filter(!category %in% prac_trials) %>%
  group_by(condition,age_numeric) %>%
  summarize(num_drawings = n()) %>%
  kable()
```

## Look at counts by category
```{r plot-counts}
cat_by_cond_by_age<- d %>%
  group_by(age_numeric,condition,category) %>%
  summarize(num_drawings = n()) 

ggplot(cat_by_cond_by_age, aes(x = age_numeric, y = num_drawings, col=condition)) +
  geom_point() +
  facet_wrap(~category)
```
```