---
title: "Count and compile classifications"
output: html_notebook
---

## Check we have values for all images
```{r}
library(here)
library(tidyverse)
```

```{r}
Layer = 'FC7'
classification_dir = here::here('data/classification_outputs/Layer6_redo')

```

```{r}
files <- dir(classification_dir) 
indexes = array()
count=0
for (f in files){
  count=count+1
  this_csv = read.csv(paste0(classification_dir,'/',f)) %>%
    mutate(batch_str = str_split_fixed(f,'_',4)[,4]) %>%
    mutate(batch = as.numeric(str_split_fixed(batch_str,'.csv',2)[,1]))
  
  if (count==1){
    all_csvs = this_csv
  }
  else {
  all_csvs <- all_csvs %>%
    full_join(this_csv, by = c("X", "index", "age", "target_label",
"session_id", "correct_or_not", "TV_prob",
"airplane_prob", "apple_prob", "bear_prob", "bed_prob",
"bee_prob", "bike_prob", "bird_prob", "boat_prob",
"book_prob", "bottle_prob", "bowl_prob", "cactus_prob",
"camel_prob", "car_prob", "cat_prob", "chair_prob",
"clock_prob", "couch_prob", "cow_prob", "cup_prob",
"dog_prob", "elephant_prob", "face_prob", "fish_prob",
"frog_prob", "hand_prob", "hat_prob", "horse_prob",
"house_prob", "ice.cream_prob", "key_prob", "lamp_prob",
"mushroom_prob", "octopus_prob", "person_prob",
"phone_prob", "piano_prob", "rabbit_prob",
"scissors_prob", "sheep_prob", "snail_prob",
"spider_prob", "tiger_prob", "train_prob", "tree_prob",
"watch_prob", "whale_prob", "batch_str", "batch") )
  }
}
```


# check no duplicates
```{R}
all_csvs_check <- all_csvs %>%
  distinct(session_id, age, target_label)
# chceck
library(assertthat)
assertthat::assert_that(length(unique(all_csvs$index)) == length(all_csvs$index))
assertthat::assert_that(length(unique(all_csvs$index)) == length(all_csvs_check$target_label))
```

# check nothing is missing
```{r}
index_full_array = seq.int(0,max(all_csvs$index),1)
index_full_array = as.tibble(index_full_array)

indexes_missing <- index_full_array %>%
  filter(!value %in% all_csvs$index)
```



```{r}
dir.create(here::here('data','compiled_classifications'))
num_batches = length(unique(all_csvs$batch))
write.csv(all_csvs, here::here('data','compiled_classifications/',paste0(Layer,'batchtotal_',as.character(num_batches),'.csv')))


```