---
title: "main_analysis"
author: "Bria Long"
date: "9/23/2020"
output: html_document
---


# Libraries
# Load classification data
# Load meta-data from mongodb


```{r}

## Load metadata and merge with classificatinos
practice_categories = c('shape','this circle','square','this square','something you love')
extra_prompt = c('something you love')

## Load in meta data from mongo-db database dumps
meta_cdm_run_v4 <- read.csv(here::here('data/drawings/cogsci_2019/filtered_dataset_descriptives/MuseumStation_AllDescriptives_7200_images_cdm_run_v4.csv')) %>%
  as.tibble() 

cogsci_2019_meta <- read.csv(here::here('data/drawings/cogsci_2019/filtered_dataset_descriptives/MuseumStation_AllDescriptives_20780_images_final_cdm_run_v3.csv')) %>%
  select(-X) %>%
  as.tibble() %>%
  full_join(meta_cdm_run_v4) %>%
  filter(!category %in% practice_categories) %>%
  filter(!category %in% extra_prompt) %>%
  mutate(category_long = category) %>%
  mutate(category = str_split_fixed(category," ",2)[,2]) %>%
  mutate(draw_duration = draw_duration_old) # use version of drawing duration from 1st to last stroke since same across dataset
```

```{r}

all_meta = cogsci_2019_meta
# compile metadata
which_run = c('cdm_run_v4','cdm_run_v5','cdm_run_v6','cdm_run_v7')
for (run in which_run){
this_run_meta = read.csv(here::here('data/drawings/stringent_cleaned_dataset_meta', paste0(run, '_cleaned.csv'))) %>%
  as.tibble() %>%
  select(-games, -numGames)

  all_meta <- all_meta %>%
    full_join(this_run_meta)
  
}

```

```{r load-classifications}
## Load classification data
classification_data <- read.csv('../../data/cogsci_2019/classification-outputs/Classification_Outputs8694.csv') %>%
  as.tibble() %>%
  mutate(session_id = paste('cdm_',session_id,sep="")) %>%
  mutate(age_numeric = age) %>%
  mutate(age = paste('age',age,sep="")) %>%
  mutate(age = as.factor(age)) %>%
  mutate(category = target_label) %>% 
  mutate(image_name = paste(category,'_sketch_', age,'_', session_id,'.png',sep="")) %>%
  select(-X) 
```