---
title: "Dispersion_plot_and_stats"
author: "Bria Long"
date: "9/30/2020"
output: html_document
---
# Libraries and data
```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(assertthat)
library(ggthemes)
library(egg)
library(viridis)
library(langcog)
```

## Load metadata

### Load frequency ratings
```{r}
frequency = read_csv(file = here::here('data/surveys/drawing_experience/preprocessed/Category_frequency_survey.csv')) %>%
  filter(childs_age > 2) # a 2-year-old's parent got in there somehow..
```


```{r}
freq_by_category <- frequency %>%
  filter(childs_age > 2) %>%
  mutate(category = str_split_fixed(category,' ',2)[,2]) %>%
  mutate(category = str_replace(category,' ','.')) %>%
  group_by(category) %>%
  summarize(drawing_frequency = mean(often_drawn_rating)) 

```

```{r}
dispersion <- read_csv(file = here::here('data/feature_space_metrics/class_dispersion_by_age.csv')) %>%
  as_tibble() %>%
  mutate(age = X1+2) %>%
  select(-X1) %>%
  filter(age >2) %>%
  gather(key=category, value=dispersion, -age) %>%
  left_join(freq_by_category)


disp_by_age <- dispersion %>%
  group_by(age) %>%
  multi_boot_standard(col = 'dispersion')
```
```{r}
ggplot(disp_by_age, aes(x=age, y=mean)) +
  theme_few() +
  geom_pointrange(aes(ymin=ci_lower, ymax=ci_upper)) + 
  geom_point(data=dispersion, aes(x=age, y=dispersion, col=category), alpha=.2) +
  geom_smooth(alpha=.01, size=.5, span=1, color='grey')

```
```{r}
ggplot(dispersion, aes(x=age, y=dispersion,col=category)) +
  theme_few() +
  geom_point(alpha=.5) +
  geom_smooth(alpha=.01, size=.5, span=10)
  
```

```{r}
dispersion_by_cat <- dispersion %>%
  group_by(category) %>%
  summarize(avg = mean(dispersion)) %>%
  arrange(avg) %>%
  kable()
```

```{r}
d_model = lmer(data=dispersion, dispersion ~ scale(age) + drawing_frequency + (1|category))
d_model_summary = summary(d_model)

age_effect= round(d_model_summary$coefficients[2,],2)
freq_effect = round(d_model_summary$coefficients[3,],2)
```

