---
title: "Count and compile classifications"
output: html_notebook

---

## Check we have values for all images
```{r}
library(tidyverse)
classification_dir = "classification-outputs-vehiclegame_C_0.1"
# classification_dir = "classification-outputs-biganimalgame_C_0.1"
# classification_dir =  "classification-outputs-objectgame_C_0.1"
files <- dir(classification_dir) 
indexes = array()
count=0
for (f in files){
  count = count +1
  this_csv = read.csv(paste0(classification_dir,'/',f)) 
  indexes[count] = this_csv$index
}
```

```{r}
index_full_array = seq.int(0,max(indexes),1)
index_full_array = as.tibble(index_full_array)

indexes_missing <- index_full_array %>%
  filter(! value %in% indexes)
```

## Make joined CSV
```{r}

files <- dir(classification_dir) 
indexes = array()
options(warn=-1) # lots of warningss for full_join over and over even though it's fine

count=0
for (f in files){
  count = count +1
  this_csv = read.csv(paste0(classification_dir,'/',f)) 
  if (count==1){
    all_data = this_csv
  }
  all_data <- all_data %>%
    full_join(this_csv)
}
```



```{r}
write.csv(all_data, paste0('compiled_classifications/',classification_dir,'_',count,'.csv'))

```