---
title: "extra-analyses"
author: "Bria Long"
date: "1/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
base_size_chosen = 16
## Compute target_label_prob averages within quantiles / age
num_quantiles = 10
# 
# # compute quantiles without knowing about age
d_tracing <- d %>%
  filter(!is.na(avg_tracing_rating)) %>%
  mutate(avg_spatial_quantile = ntile(avg_spatial,num_quantiles)) %>%
  mutate(avg_shape_quantile = ntile(avg_shape,num_quantiles)) %>%
  mutate(avg_tracing_rating_quantile = ntile(avg_tracing_rating,num_quantiles))
# 
ggplot(d_tracing, aes(avg_tracing_rating,correct_or_not,color=age_numeric)) +
  geom_jitter(alpha=.2, height=.1, width=.1) +
  theme_few(base_size = base_size_chosen) +
  labs(x='Normalized tracing score', y='Classification accuracy') +
  scale_color_viridis(option="D") +
  theme(legend.position = "none") +
  geom_smooth(col='grey',span=20, method='lm') +
  facet_grid(~age_numeric)
```

```{r include=FALSE}
### Plot results only for unfamiliar items
unfamiliar_list = c('key','sheep','scissors','couch','bear','frog','phone')

d <- d %>%
    mutate(unfam_category = (category %in% unfamiliar_list))

cor_by_age_by_fam <- d %>%
  group_by(age_numeric,category,unfam_category) %>%
  summarize(avg_cor = mean(correct_or_not)) %>%
  group_by(age_numeric, unfam_category) %>%
  multi_boot_standard(col = "avg_cor")  

ggplot(cor_by_age_by_fam, aes(age_numeric,mean, color=unfam_category)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), position=position_dodge(width=.5)) + 
  theme_few(base_size = base_size_chosen) + 
  labs(x='Age', y='Classification accuracy') +
  theme(legend.position = "none") +
  scale_x_discrete(limits=c(2,3,4,5,6,7,8,9,10)) 


```


```{r tracing-extra-stats include=FALSE}
# Try spatial/shape tracing metrics separately to confirm results
mod_tracing <- glmer(correct_or_not ~ scale(age_numeric) +
                          scale(draw_duration]) +
                          scale(mean_intensity) +
                          scale(num_strokes) +
                          scale(avg_spatial)*scale(avg_shape) + 
                        (1|session_id) +
                        (1|category),
      data = d,  family="binomial")

mod_tracing <- glmer(correct_or_not ~ scale(age_numeric) +
                          scale(draw_duration) +
                          scale(mean_intensity) +
                          scale(num_strokes) +
                          scale(avg_spatial)*scale(avg_shape) + 
                        (1|session_id) +
                        (1|category),
      data = d,  family="binomial")

```


```{r include=FALSE}

## Plots where every dot = 1 drawing, too overwhelming

ggplot(d, aes(age_numeric,target_label_prob, color=age_numeric)) +
  geom_jitter(alpha=.1, width=.2) + 
  theme_few(base_size = base_size_chosen) +
  labs(x='Age', y='Probability') +
  scale_color_viridis(option="D") +
  theme(legend.position = "none") + 
  geom_smooth(method='lm', color = "grey")

ggplot(d, aes(age_numeric,correct_or_not, color=age_numeric)) +
  geom_jitter(alpha=.05, width=.2, height=.1) + 
  theme_few(base_size = base_size_chosen) +
  labs(x='Age', y='Probability') +
  scale_color_viridis(option="D") +
  theme(legend.position = "none") + 
  geom_smooth(method='lm', color = "grey")




```


```{r  include=FALSE}
## No age effect in draw duration controlling for other covariates
draw_duration_model <- lmer(draw_duration ~ scale(age_numeric) +
                          scale(num_strokes) +
                          scale(mean_intensity) +
                        (1|session_id) +
                        (1|category),
      data = d)
draw_duration_model_out=summary(draw_duration_model)

```

```{r include=FALSE}
## Children's drawings become more detailed as they get older
mean_intensity_model <- lmer(mean_intensity ~ scale(age_numeric) +
                          scale(draw_duration) +
                          scale(num_strokes) +
                        (1|session_id) +
                        (1|category),
      data = d)
mean_intensity_model_out=summary(mean_intensity_model)
```

```{r include=FALSE}
## Small age effect in num strokes controlling for covariates
num_strokes_model <- lmer(num_strokes ~ scale(age_numeric) +
                          scale(draw_duration) +
                          scale(mean_intensity) +
                        (1|session_id) +
                        (1|category),
      data = d)
num_strokes_model_out=summary(num_strokes_model)
```
