---
title: "Preprocess drawing frequency survey data"
author: ""
date: "8/27/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(ggthemes)
library(knitr)

```
# Load and preprocess data
```{r}
raw = read_csv(here('data','surveys','drawing_experience','raw','Drawing Experience Survey_August 28, 2020_13.58.csv'))
```

## Loop through question nnames and preproces qualtrics data
```{r}
question_names <- raw %>%
  select(contains('Q3_')) %>%
  filter(row_number()==1) 

question_ids = colnames(question_names)
categories = str_split_fixed(question_names[1,],'-',2)[,2]
categories = str_split_fixed(categories,' ',2)[,2]

# data.frame(categories, question_ids)
new_colnames = c('childs_age', 'subject_id', categories)

d <- raw %>%
  filter(DistributionChannel != 'preview') %>% # not preview
  filter(Q8 == 1) %>% # positive consen
  filter(!Q3_2 == 'NA') %>%## no NAs, i.e. complete
  mutate(childs_age = Q16) %>%
  select(childs_age, ResponseId,contains('Q3_'))

colnames(d) <- new_colnames

d_long <- gather(d, key='category', categories, -childs_age, -subject_id) %>%
  rename(often_drawn_rating = categories)
  
```
## to check duration of experiment
```{r}
# time_out <- raw %>%
#   select(`Duration (in seconds)`) %>%
#   rename(s = `Duration (in seconds)`) %>%
#   mutate(s = as.numeric(s)) %>%
#   filter(s>100) 
# 
# ggplot(time_out, aes(y=s/60)) +
#   geom_boxplot()
```

## Check # of participants by child's age
```{r}
count_by_age <- d_long %>%
  group_by(childs_age) %>%
  dplyr::summarize(num_surveys = n())

```

## Preprocess data; make numeric
```{r}
d_long <- d_long %>%
  mutate(often_drawn_rating = as.numeric(often_drawn_rating), childs_age = as.numeric(childs_age), category = factor(category))
```

## Save it out
```{r}
dir.create(here::here('data/surveys/drawing_experience/preprocessed'))
write_csv(d_long, here::here('data/surveys/drawing_experience/preprocessed/Category_frequency_survey.csv'))
```


# Basic descriptives
## Compute averages by category/age and visualize
```{r}
avg_by_category_age <- d_long %>%
  mutate(often_drawn_rating = as.numeric(often_drawn_rating), childs_age = as.numeric(childs_age), category = factor(category)) %>%
  group_by(category, childs_age) %>%
  summarize(avg_rating = mean(often_drawn_rating)) %>%
  ungroup() %>%
  mutate(category = fct_reorder(category, avg_rating, .desc =TRUE))

avg_by_category <- d_long %>%
  mutate(often_drawn_rating = as.numeric(often_drawn_rating), childs_age = as.numeric(childs_age), category = factor(category)) %>%
  group_by(category) %>%
  summarize(avg_rating = mean(often_drawn_rating)) %>%
  ungroup() %>%
  mutate(category = fct_reorder(category, avg_rating, .desc =TRUE))
```

```{r}
ggplot(avg_by_category, aes(x=category, y=avg_rating, col=category)) + 
  geom_point()  +
  theme_few()  + 
  theme(axis.text.x = element_text(angle = 90))   + 
  labs(title = 'Ratings of how frequently children draw objects', subtitle = ('1 = Never, 2=Once or Twice, 3=A few times, 4=Frequently, 5=Nearly every time they draw'), y = 'Avg Frequency Drawn', x = 'Category') +
  theme(legend.position = 'none') 

```

```{r}
ggplot(avg_by_category_age, aes(x=childs_age, y=avg_rating, col=category)) + 
  geom_point()  +
  geom_jitter(height=.1, width=.1, data=d_long, aes(x=childs_age, y=often_drawn_rating), alpha=.2) +
  geom_smooth() +
  theme_few()  + 
  theme(axis.text.x = element_text(angle = 90))   + 
  labs(title = 'Ratings of how frequently children draw objects', subtitle = ('1 = Never, 2=Once or Twice, 3=A few times, 4=Frequently, 5=Nearly every time they draw'), y = 'Avg Frequency Drawn', x = 'Category') +
  facet_wrap(~category) +
  theme(legend.position = 'none') 
  
  
```